steps:
  # ============================
  # 🔹 BACKEND
  # ============================
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=${_BACKEND_IMAGE}:${SHORT_SHA}
      - --tag=${_BACKEND_IMAGE}:latest
      - backend

  - id: push-backend-short-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_BACKEND_IMAGE}:${SHORT_SHA}

  - id: push-backend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_BACKEND_IMAGE}:latest

  - id: deploy-backend
    name: gcr.io/cloud-builders/gcloud
    waitFor:
      - push-backend-short-sha
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image=${_BACKEND_IMAGE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --quiet

  # ============================
  # 🔹 FRONTEND
  # ============================
  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - --file=frontend/Dockerfile
      - --build-arg=NEXT_PUBLIC_API_BASE_URL=${_API_BASE_URL}
      - --build-arg=NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}
      - --tag=${_FRONTEND_IMAGE}:${SHORT_SHA}
      - --tag=${_FRONTEND_IMAGE}:latest
      - frontend

  - id: push-frontend-short-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_FRONTEND_IMAGE}:${SHORT_SHA}

  - id: push-frontend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_FRONTEND_IMAGE}:latest

  - id: deploy-frontend
    name: gcr.io/cloud-builders/gcloud
    waitFor:
      - push-frontend-short-sha
    args:
      - run
      - deploy
      - ${_FRONTEND_SERVICE}
      - --image=${_FRONTEND_IMAGE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --quiet

# ============================
# 🔹 VARIABLES
# ============================
substitutions:
  _AR_REPO: europe-southwest1-docker.pkg.dev/observatorio-dev/repo-observatorio-dev
  _BACKEND_IMAGE: ${_AR_REPO}/backend
  _FRONTEND_IMAGE: ${_AR_REPO}/frontend
  _REGION: europe-southwest1
  _BACKEND_SERVICE: backend-dev
  _FRONTEND_SERVICE: frontend-dev
  _API_BASE_URL: https://backend-970552335718.europe-southwest1.run.app
  _GOOGLE_CLIENT_ID: ""

# ============================
# 🔹 IMÁGENES RESULTANTES
# ============================
images:
  - ${_BACKEND_IMAGE}:${SHORT_SHA}
  - ${_BACKEND_IMAGE}:latest
  - ${_FRONTEND_IMAGE}:${SHORT_SHA}
  - ${_FRONTEND_IMAGE}:latest

# ============================
# 🔹 OPCIONES
# ============================
options:
  logging: CLOUD_LOGGING_ONLY
