steps:
<<<<<<< HEAD
  # ============================
  # 🔹 BACKEND
  # ============================
=======
>>>>>>> 2fc272d7544d0eae9c19b424ade8c7224aabf6e1
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=backend/Dockerfile
      - --tag=${_BACKEND_IMAGE}:${SHORT_SHA}
      - --tag=${_BACKEND_IMAGE}:latest
      - backend

  - id: push-backend-short-sha
    name: gcr.io/cloud-builders/docker
<<<<<<< HEAD
    args:
      - push
      - ${_BACKEND_IMAGE}:${SHORT_SHA}

  - id: push-backend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_BACKEND_IMAGE}:latest

  # ============================
  # 🔹 FRONTEND
  # ============================
=======
    args: ["push", "${_BACKEND_IMAGE}:${SHORT_SHA}"]

  - id: push-backend-latest
    name: gcr.io/cloud-builders/docker
    args: ["push", "${_BACKEND_IMAGE}:latest"]

>>>>>>> 2fc272d7544d0eae9c19b424ade8c7224aabf6e1
  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
<<<<<<< HEAD
      - --no-cache
      - --file=frontend/Dockerfile
      - --build-arg=NEXT_PUBLIC_API_BASE_URL=${_API_BASE_URL}
=======
      - --file=frontend/Dockerfile
>>>>>>> 2fc272d7544d0eae9c19b424ade8c7224aabf6e1
      - --tag=${_FRONTEND_IMAGE}:${SHORT_SHA}
      - --tag=${_FRONTEND_IMAGE}:latest
      - frontend

  - id: push-frontend-short-sha
    name: gcr.io/cloud-builders/docker
<<<<<<< HEAD
    args:
      - push
      - ${_FRONTEND_IMAGE}:${SHORT_SHA}

  - id: push-frontend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_FRONTEND_IMAGE}:latest

# ============================
# 🔹 VARIABLES
# ============================
=======
    args: ["push", "${_FRONTEND_IMAGE}:${SHORT_SHA}"]

  - id: push-frontend-latest
    name: gcr.io/cloud-builders/docker
    args: ["push", "${_FRONTEND_IMAGE}:latest"]

>>>>>>> 2fc272d7544d0eae9c19b424ade8c7224aabf6e1
substitutions:
  _AR_REPO: europe-southwest1-docker.pkg.dev/observatorio-dev/repo-observatorio-dev
  _BACKEND_IMAGE: ${_AR_REPO}/backend
  _FRONTEND_IMAGE: ${_AR_REPO}/frontend
<<<<<<< HEAD
  _API_BASE_URL: https://backend-970552335718.europe-southwest1.run.app

# ============================
# 🔹 IMÁGENES RESULTANTES
# ============================
=======

>>>>>>> 2fc272d7544d0eae9c19b424ade8c7224aabf6e1
images:
  - ${_BACKEND_IMAGE}:${SHORT_SHA}
  - ${_BACKEND_IMAGE}:latest
  - ${_FRONTEND_IMAGE}:${SHORT_SHA}
  - ${_FRONTEND_IMAGE}:latest

<<<<<<< HEAD
# ============================
# 🔹 OPCIONES
# ============================
options:
  logging: CLOUD_LOGGING_ONLY
=======
options:
  logging: CLOUD_LOGGING_ONLY
>>>>>>> 2fc272d7544d0eae9c19b424ade8c7224aabf6e1
